### ISSUE TITLE
consult-notes-file-dir-sources

### ISSUE THREAD

**Issue by MarcRohrer** [mclear-tools/consult-notes#52] opened 2024-01-16 14:16 UTC
Hi,

I have various subdirectories in my denote directory 
and i would like to use narrowing for that.

Works fine, but I only have filenames when setting
my subdirectories ewith

consult-notes-file-dir-sources

How can I set the beautyful format set when using
(consult-notes-denote-mode)?

best wishes!

Marc

**Comment by mclearc** [comment] 2024-01-20 13:44
Hi -- I'm not sure I fully understand. The file search function is just that, it doesn't include directories in the list along with the filenames. But directory names should be visible as headings which you can move through via C-n/p. But maybe I'm not understanding what you're asking...

**Comment by mclearc** [comment] 2024-02-09 19:17
I'm not entirely sure what's happening here. But here are some things to keep in mind or try:

- Use `(consult-notes-denote-display-id nil)` to remove display of IDs
- If you're searching org files (and have `consult-notes-org-headings-mode` enabled) you might want to set the org headings files, which use a specific function and variable to set things up for consult -- e.g.  `(setopt consult-notes-org-headings-files `(,(concat org-directory "/inbox.org")))`
- Look at the values for annotation; e.g. `consult-notes-file-dir-annotate-function` and the functions `(consult-notes-denote--annotate)` and `(consult-notes-org-headings-annotations)`

**Comment by MarcRohrer** [comment] 2024-02-14 14:09
Hi,

to me it looks like the entries simply are the complete filename...

- ```(consult-notes-denote-display-id nil)``` does not change anything :-(
- I do not use ```consult-notes-org-headings-mode```
- when I set ```consult-notes-file-dir-annotate-function``` to one of the mentioned function I only get an error 
```Error in post-command-hook (vertico--exhibit): (wrong-number-of-arguments (1 . 1) 3)```

Do I understand it correctly, that the annotation function only handles the part, which comes after the filename? At least, that is my impression looking at ```consult-notes-denote--annotate```. After that, there is the directory, which is redundant to the source. Well almost.

I would prefer not having the id listed but only title, keywords, source. Size and time als do not really matter for me. Can this be achieved?

Thanx!

Marc

**Comment by mclearc** [comment] 2024-02-16 03:08
So here is what things should look like with `(setq consult-notes-denote-display-id nil)`:
<img width="1091" alt="Screenshot 2024-02-15 at 21 47 59" src="https://github.com/mclear-tools/consult-notes/assets/1502422/ede3a333-7066-4cec-949f-7fa287f3efd3">

I just pushed commit https://github.com/mclear-tools/consult-notes/commit/e99e92fe70aa18e4e6f00e912be4c3bacd8a8f66, which allows you to set the function for annotation. In your case I think what you want is to do `(setq consult-notes-denote-file-dir-annotate-function nil)`

After which denote should look like this:
<img width="1091" alt="Screenshot 2024-02-15 at 22 08 30" src="https://github.com/mclear-tools/consult-notes/assets/1502422/a8c76293-4f00-46b2-92ca-085549b04530">

**Comment by MarcRohrer** [comment] 2024-02-16 06:11
Hi,

My current configuration

```
  (use-package consult-notes
    :config
    (consult-notes-denote-mode)
    (global-set-key (kbd "S-C-n") 'consult-notes)
    (global-set-key (kbd "M-n") 'consult-notes-search-in-all-notes))

  (setq consult-notes-denote-display-id nil)
  (setq consult-notes-denote-annotate-function nil)
```
looks like this:

![grafik](https://github.com/mclear-tools/consult-notes/assets/110817144/a645a19b-c65c-4fb2-a423-07de31e7d29d)

It looks like ``` (setq consult-notes-denote-display-id nil)``` does not show the intended impact? 
I am unclear, how the MELPA infrastructure works, is this in in 20240216.311, that I just installed?

Thank you so much for your help!

Marc

**Comment by mclearc** [comment] 2024-02-16 17:14
Yep -- the most recent version is on Melpa. 

From the screenshot it isn't clear to me that `(consult-notes-denote-mode)` is active. A couple things to check:

1. Make sure the var `consult-notes-denote-mode` is non-nil 
2. Try loading denote *before* loading consult-notes 
3. Put `(setq consult-notes-denote-display-id nil)` and  `(setq consult-notes-denote-annotate-function nil)` in the `:config` block of your use-package setup

**Comment by mclearc** [comment] 2024-02-16 17:20
Looking back at your original message I see the same problem with your config block -- i.e. you're calling `consult-notes-denote-mode` outside the use-package block, but presumably before you've initialized the package (which is automatically deferred until the `:after` condition is satisfied). If you want to call config options for the package prior to its loading you need to conditionalize like so:  

```emacs-lisp
(with-eval-after-load 'consult-notes
                         
(consult-notes-denote-mode)
(global-set-key (kbd "S-C-n") 'consult-notes)
(global-set-key (kbd "M-n") 'consult-notes-search-in-all-notes)

(setq consult-notes-file-dir-sources '(("Emacs"      ?e  "~/notes/emacs")
                                       ("JavaScript" ?j  "~/notes/js")
                                       ("Jupyter"    ?y  "~/notes/jupyter"))))
```

**Comment by MarcRohrer** [comment] 2024-02-19 06:17
Hi,

I changed the code to what I understood:

```
(use-package denote
    :init
    (setq denote-directory "h:/src/emacs/notes")
    (setq denote-known-keywords '("component" "project" "idea" "report" "emacs" "function" "memory" "ressource" "internal" "external"))
    (add-hook 'find-file-hook #'denote-link-buttonize-buffer)
    (setq denote-prompts '(subdirectory title keywords))
    (global-set-key (kbd "C-n") 'denote))

  (use-package consult-notes
    :config
    (setq consult-notes-denote-display-id nil)
    (setq consult-notes-denote-annotate-function nil))

  (with-eval-after-load 'consult-notes
    (consult-notes-denote-mode)
    (global-set-key (kbd "S-C-n") 'consult-notes)
    (global-set-key (kbd "M-n") 'consult-notes-search-in-all-notes)
    (setq consult-notes-file-dir-sources '(("Emacs"      ?e  "h:/src/emacs/notes/emacs")
                                           ("Web"        ?j  "h:/src/emacs/notes/web")
                                           ("Jupyter"    ?y  "h:/src/emacs/notes/jupyter"))))
```

But unfortunately things do not look different at all :-(

![consult-notes](https://github.com/mclear-tools/consult-notes/assets/110817144/055a788c-38ef-4201-8c7c-50e53756a626)

The variables seem set:

```
consult-notes-denote-display-id is a variable defined in ‘consult-notes-denote.el’.

Its value is nil
Original value was t
```

and

```
consult-notes-denote-annotate-function is a variable defined in ‘consult-notes-denote.el’.

Its value is nil
Original value was 
‘consult-notes-denote--annotate’
```

Thank you very much!

Marc

**Comment by mclearc** [comment] 2024-02-20 18:18
It still looks lie consult-notes-denote-mode isn't active. Can you check whether that minor mode is non-nil?

**Comment by MarcRohrer** [comment] 2024-03-04 14:03
I just "accidentally" saw that the entries are listed twice.
One as I hoped for and the other one as stated above.

Why is that?

![grafik](https://github.com/mclear-tools/consult-notes/assets/110817144/111f3da7-2a04-4139-b1a5-522f2b278800)

**Comment by mclearc** [comment] 2024-03-06 15:31
I'm still not sure what is wrong with you config -- It still looks like consult-notes-denote-mode isn't active. Can you check whether that minor mode is non-nil?

**Comment by MarcRohrer** [comment] 2024-03-08 07:16
you mean in the minibuffer?

major mode is minibuffer mode here

```
Global minor modes enabled: Auto-Encryption Beacon Blink-Cursor
Consult-Notes-Denote Cua Delete-Selection Electric-Indent
File-Name-Shadow Global-Auto-Revert Global-Centered-Cursor
Global-Company Global-Eldoc Global-Flycheck Global-Font-Lock
Global-Org-Modern Marginalia Pixel-Scroll Pixel-Scroll-Precision
Popper Recentf Savehist Show-Paren Smartparens-Global Tooltip
Transient-Mark Vertico Which-Key Winner Yas-Global
```

so consult-notes-denote seems to be active, right?

but why is the note listed twice?
It takes relatively long until the notes are shown, looks like they are read twice?

**Comment by mclearc** [comment] 2024-03-08 17:56
Unfortunately I really can't say what is going on. You might try and see if you can reproduce the problem with a blank emacs (i.e. starting with `emacs -q` and only loading the consult-notes package). If you can, then let me know what the steps were and I will see if I can reproduce it on my end.

**Comment by mclearc** [comment] 2024-04-11 02:12
I'm going to close this but reopen if you can find a way to reliably reproduce the problem.

**Closed by mclearc** 2024-04-11 02:12 UTC
